# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc77b747805b441886023c39559629d5094bac3f1c0afda1b1b309e71e8b2b64eba179f5c360f771c4edbcee22635f14406a7a9e4b99ace68997d85720c707bb

test:
  secret_key_base: 9ce68d51e9337c3990019c409a7d2e7dae43388c0ce5e6d1e86de2edcafdfb6994df5c40af16e099ba0c19893c252ab5ca1171bdfb59401852ba6358afde09b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
